### ISSUE TITLE
Misleading Information about Linux Devices in "Initial ESP flashing" Manual

### ISSUE THREAD

**Issue by EarthlingX** [openbikesensor/OpenBikeSensorFirmware#240]
At least on Debian systems (checked here with Debian Buster), the recommended workflow to flash the ESP32 is **not** correctly described [in the manual](https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/master/docs/software/firmware/initial_flash.md).

**We had to get it work this way:**

1. Install package `esptool` via `apt-get update` and afterwards `apt-get install esptool` (as root!)
2. Navigate into directory where you have extracted the zip-file (e.g. `cd /home/user/Downloads/OBS`)
2. Copy and paste exactly this command (and nothing else) into the shell and run with "enter" (as root!):
```
esptool \
    --chip esp32 \
    --port /dev/ttyUSB0 \
    --baud 921600 \
    --before default_reset \
    --after hard_reset \
    write_flash -z \
    --flash_mode dio \
    --flash_freq 40m \
    --flash_size detect \
    0x1000 0x01000.bin \
    0x8000 0x08000.bin \
    0xe000 0x0e000.bin \
    0x10000 0x10000.bin
```

The subsequent flashing process worked pretty well and succeeded in all cases. However, the initial approach mentioned in the manual (with its first line `python3 esptool.py \`) did never work, it always led to "Command/file not found" or similar output in the shell.

Reason for this could be the missing file `esptool.py` in the zip-file? However, there was also no need to call `python3` anywhere - just execute `esptool`. :-)

**Comment by derSammy** [comment]
Thanks for this feedback. I face the same issue with the non-successfull Linux instruction (using Linux Mint) and solved it equivalently by (having Python3 (incl. Pip) installed) by
`sudo pip3 install esptool`
and than
`esptool.py \
  --chip esp32 \
  --port /dev/ttyUSB0 \
  ...`
Anyway, it seems to be necessary to install esptool with root privileges.

**Comment by SubOptimal** [comment]
My suggestion would be not to provide a distro-specific command as general advice.

- leave the command in the documentation as is; it would support users not familiar with Linux to know for which tool to search for their distribution (`esptool.py`) and (if needed) to install Python 3 (and not Python 2)
- to provide even more help, we could add a hint section for some Linux distributions to reflect the differences 

**Debian**
- as root `apt-get install esptool`
- call `esptool` instead of `python3 esptool.py`
-`/usr/bin/esptool` is a soft link to `/usr/share/esptool/esptool.py`, which the Python 3 interpreter executes

**Arch**
- as root `pacman -S esptool`
- call `esptool.py` instead of `python3 esptool.py`
- `/usr/bin/esptool.py` is the script itself, which the Python 3 interpreter executes

We might provide a general solution for distributions not providing a package to install `esptool.py`. It seems Mint is such a case. On the website http://packages.linuxmint.com/ no package is found for the term "esptool".
Here we should avoid suggesting the solution `sudo pip3 install esptool` as this can break the package manager of the distribution.

**Comment by opatut** [comment]
We could also leave a hint that, if you don't mind the bigger disk size it requires, compiling yourself and flashing through `platformio` is rather convenient and pretty much failsafe. 

* install platformio tools for your distro
* clone the firmware repo
* run `pio run -t upload` from the repository

**Comment by amandel** [comment]
With https://install.openbikesensor.org/ no platform specific setup for the initial installation is needed any more. So I close this.

**Comment by boldt** [comment]
Should we add https://install.openbikesensor.org/ to https://www.openbikesensor.org/docs/hardware/v00.03.12/build-instructions/#schritt-18-elektronik-testen as well?

**Comment by amandel** [comment]
Is the install / flash part not covered at all? Sure, why not.

**Comment by opatut** [comment]
Now it is: https://openbikesensor.org/flash

We should just add a fourth section there, IMO, `Flash from Browser`
