### ISSUE TITLE
Sources for external libs not mentioned

### ISSUE THREAD

**Issue by Halbelunge** [openbikesensor/OpenBikeSensorFirmware#89]
The external libs, like SSD1306.h are not mentioned to install. So there is no source for these mentioned (there are multiple ones as an option).

Maybe it is better, to include them into the project instead of rely on external git repos.

**Comment by boldt** [comment]
* [The libs are described here](https://github.com/Friends-of-OpenBikeSensor/Friends-of-OpenBikeSensor.github.io/blob/master/software/firmware/setup.md)
* [We use platformIO, which handles the dependencies](https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/blob/master/platformio.ini) (see #24) --> Including them directly is a bad idea, since it will increase the size of the repo by 3rd party libs.

I assume, we can close this issue.

**Comment by boldt** [comment]
TODO: Add some notes to the github pages

**Comment by amandel** [comment]
I guess this can be closed - there is already documentation for platform.io setup.
